export {default as Tick} from './TickSVG'
export {default as Share} from './ShareSVG'
export {default as Chevrone} from './ChevroneSVG'
export {default as Heart} from './HeartSVG'
export {default as Play} from './PlaySVG'
export {default as Add} from './AddAllSVG'
export {default as ArrowsVertical} from './ArrowsVerticalSVG'
export {default as Search} from './SearchSVG'